replicaCount: 1

pdb:
  minAvailable: 1

image:
  repository: helloworld
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

additionalEnv: {}
#  - name: myvar
#    value: AAAAAAAAAAAAAAAA

podAnnotations: {}
  #ad.datadoghq.com/helloworld.check_names: '["openmetrics"]'
  #ad.datadoghq.com/helloworld.init_configs: "[{}]"
  #ad.datadoghq.com/helloworld.instances: '[{"prometheus_url":"http://%%host%%:9091/metrics","namespace":"helloworld","metrics":["http_*","promhttp_*","go_goroutines"]}]'
  #config.linkerd.io/skip-outbound-ports: 8126,6379

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port:
    grpc: 7071
    http: 8081
    metrics: 9091

ingressRoute:
  enabled: true
  route: /service/helloworld/

resources: {}

autoscaling: {}

appconfig: {}