replicaCount: 1

pdb:
  minAvailable: 1

image:
  repository: helloworld
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

additionalEnv: {}
#  - name: myvar
#    value: AAAAAAAAAAAAAAAA

podAnnotations: {}
  #ad.datadoghq.com/helloworld.check_names: '["openmetrics"]'
  #ad.datadoghq.com/helloworld.init_configs: "[{}]"
  #ad.datadoghq.com/helloworld.instances: '[{"prometheus_url":"http://%%host%%:9091/metrics","namespace":"helloworld","metrics":["http_*","promhttp_*","go_goroutines"]}]'
  #config.linkerd.io/skip-outbound-ports: 8126,6379

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port:
    - name: grpc
      containerPort: 7071
    - name: http
      containerPort: 8081
    - name: metrics
      containerPort: 9091

ingressRoute:
  enabled: true
  route: /service/helloworld/
  ingress1:
    nameExtension: -internal
    class: traefik-internal
    priority: "1"
  ingress2:
    nameExtension:
    class: traefik 
    priority: "2"

envNameExtension: -DB-PASSWORD 

secretKeyRef:
  nameExtension: -db-pass
  keyType: password

livenessProbe:
  portType: api

readinessProbe:
  path: /readyz
  portType: api

resources: {}

autoscaling: {}

appconfig: {}