apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tgc-common.fullname" . }}
  labels:
    {{- include "tgc-common.labels" . | nindent 4 }}
data:
  config.yml:
    {{ .Values.appconfig | toYaml | quote }}  