apiVersion: v1
kind: Service
metadata:
  name: {{ include "tgc-common.fullname" . }}
  labels:
    {{- include "tgc-common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports}}
    - name: {{ .Values.service.port.name }}
      containerPort: {{ .Values.service.port.containerPort }}
      protocol: TCP
  {{- end }}
  selector:
    {{- include "tgc-common.selectorLabels" . | nindent 4 }}
