apiVersion: v1
kind: Service
metadata:
  name: {{ include "tgc-common.fullname" . }}
  labels:
    {{- include "tgc-common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.port.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "tgc-common.selectorLabels" . | nindent 4 }}
